### ISSUE TITLE
File templates/default/a2ensite.erb does not exist for cookbook apache2

### ISSUE THREAD

**Issue by nusnewob** [svanzoest-cookbooks/apache2#402]
I have a simple recipe to include apache2 cookbook
```
include_recipe 'apache2'
```
Error in test-kichen:
```
         * link[/usr/sbin/a2ensite] action delete[2016-01-13T11:17:57+00:00] INFO: Processing link[/usr/sbin/a2ensite] action delete (apache2::default line 59)
        (skipped due to only_if)
       [2016-01-13T11:17:57+00:00] DEBUG: Skipping link[/usr/sbin/a2ensite] due to only_if ruby block
         * template[/usr/sbin/a2ensite] action create[2016-01-13T11:17:57+00:00] INFO: Processing template[/usr/sbin/a2ensite] action create (apache2::default line 64)
       [2016-01-13T11:17:57+00:00] DEBUG: Providers for generic template resource enabled on node include: [Chef::Provider::Template]
       [2016-01-13T11:17:57+00:00] DEBUG: Provider for action create on resource template[/usr/sbin/a2ensite] is Chef::Provider::Template


           ================================================================================
           Error executing action `create` on resource 'template[/usr/sbin/a2ensite]'
           ================================================================================

           RuntimeError
           ------------
           File templates/default/a2ensite.erb does not exist for cookbook apache2

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cookbooks/apache2-3.1.0/recipes/default.rb

            64:   template "/usr/sbin/#{modscript}" do
            65:     source "#{modscript}.erb"
            66:     mode '0700'
            67:     owner 'root'
            68:     group node['apache']['root_group']
            69:     action :create
            70:   end
            71: end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cookbooks/apache2-3.1.0/recipes/default.rb:64:in `block in from_file'

           template("/usr/sbin/a2ensite") do
             action [:create]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             path "/usr/sbin/a2ensite"
             backup 5
             atomic_update true
             source "a2ensite.erb"
             declared_type :template
             cookbook_name :apache2
             recipe_name "default"
             owner "root"
             group "root"
             mode "0700"
           end

       [2016-01-13T11:17:57+00:00] INFO: Running queued delayed notifications before re-raising exception
       [2016-01-13T11:17:57+00:00] DEBUG: Re-raising exception: RuntimeError - template[/usr/sbin/a2ensite] (apache2::default line 64) had an error: RuntimeError: File templates/default/a2ensite.erb does not exist for cookbook apache2
       /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/cookbook/file_system_file_vendor.rb:52:in `get_filename'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/cookbook_version.rb:332:in `preferred_filename_on_disk_location'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/provider/template_finder.rb:40:in `find'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/provider/template/content.rb:32:in `template_location'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/provider/template.rb:49:in `block in define_resource_requirements'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/mixin/why_run.rb:315:in `assert'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/provider/template.rb:47:in `define_resource_requirements'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/provider.rb:131:in `run_action'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/resource.rb:596:in `run_action'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/runner.rb:74:in `run_action'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/runner.rb:106:in `block (2 levels) in converge'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/runner.rb:106:in `each'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/runner.rb:106:in `block in converge'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
       12.6.0/lib/chef/runner.rb:105:in `converge'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/client.rb:658:in `block in converge'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/client.rb:653:in `catch'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/client.rb:653:in `converge'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/client.rb:692:in `converge_and_save'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/client.rb:271:in `run'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application.rb:261:in `block in fork_chef_client'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application.rb:249:in `fork'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application.rb:249:in `fork_chef_client'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application.rb:215:in `block in run_chef_client'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/local_mode.rb:44:in `with_server_connectivity'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application.rb:203:in `run_chef_client'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application/solo.rb:286:in `block in interval_run_chef_client'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application/solo.rb:275:in `loop'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application/solo.rb:275:in `interval_run_chef_client'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application/solo.rb:253:in `run_application'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application.rb:58:in `run'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/bin/chef-solo:25:in `<top (required)>'
         /opt/chef/bin/chef-solo:54:in `load'
         /opt/chef/bin/chef-solo:54:in `<main>'
```

**Comment by drpebcak** [comment]
https://github.com/svanzoest-cookbooks/apache2/blob/master/templates/default/a2ensite.erb

What platform are you running this on? Can you reproduce it by only including `apache2::default` in your runlist?

**Comment by Padam87** [comment]
Same here. Ubuntu 14.04

**Comment by Padam87** [comment]
Looks like this is a chef-solo specific issue. You cannot use the default berks install, you have to vendorize.

**Comment by svanzoest** [comment]
Thanks @Padam87. If there anything we could do better to help with that let us know.
